    const PREDEFINED_KEYWORDS = {
      1: ['16 x', '32 x', 'road', 'raised'],
      3: ['1 x', '2 x', '3 x', '4 x', 'slope'],
      4: ['animal', 'cat', 'dog', 'tree', 'horse', 'flower', 'plate', 'window', 'door', 'fence'],
      5: ['braille'],
      6: ['curved', 'sloped'],
      7: ['pod', 'box'],
      8: [],
      9: ['rounded'],
      11: ['1 x', '2 x', '3 x', '4 x', '5 x', '6 x', '8 x', '10 x'],
      12: ['connector', 'axle', 'holes'],
      13: ['body', 'microfig', 'legs'],
      14: ['1 x', '2 x', '3 x', '4 x', '6 x', '8 x', '10 x'],
      15: ['tile', 'pentagonal', 'power', 'shield'],
      16: ['window', 'glass', 'door'],
      17: ['card', 'trading', '1', 'game', 'ninjago', 'set', '2', 'deck', 'activity', 'the'],
      18: ['2 x', 'hinge', '1 x', '6 x', '4 x', 'locking', 'fingers', '3 x'],
      19: ['2 x', '1 x', '4 x'],
      20: ['round', 'dome', 'cone', 'roof', 'corner', 'pipe', 'hemisphere'],
      21: ['dish', 'inverted', 'radar'],
      22: [],
      23: ['panel', 'corner', 'window'],
      24: [],
      25: ['technic', 'steering', 'spring', 'shock', 'absorber', 'joint'],
      26: ['disc', 'rotor', 'ball', 'stick', 'gearbox', 'cable'],
      27: ['sports', 'musical', 'book', 'coin', 'equipment', 'wing', 'bag', 'bottle', 'plate', 'glass', 'mug'],
      28: ['dog', 'cat', 'horse', 'dinosaur', 'bird', 'fish', 'dolphin', 'bear', 'pig'],
      29: ['wheel', 'tyre', 'train', 'bicycle', 'motorcycle'],
      30: ['hose', 'rigid'],
      31: ['string', 'chain', 'rubber'],
      32: ['bar', 'fence', 'ladder', 'lever', 'stair', 'step', 'antenna'],
      33: ['rock', 'crystal'],
      34: ['support', 'crane', 'hook'],
      35: ['sail', 'boat', 'propeller', 'helicopter', 'tail', 'anchor', 'cockpit', 'airplane', 'hull', 'wing'],
      36: ['wheel', 'train', 'motorcycle', 'track', 'seat', 'mudguard', 'forklift', 'bicycle', 'base'],
      37: ['slope', '2 x', '3 x', '1 x', '4 x', '5 x', '6 x', '8 x', 'arch'],
      38: ['flag', 'road sign'],
      39: [],
      40: [],
      41: ['mask', 'head', 'weapon', 'limb', 'torso', 'cape', 'hand', 'foot', 'leg', 'arm', 'shield', 'wing', 'helmet'],
      42: ['scala', 'belville', 'fabuland'],
      43: [],
      44: [],
      45: ['motor', 'light', 'sensor', 'cable', 'wire'],
      46: [],
      47: ['windscreen', 'curved', '1 x', '2 x', '3 x', '4 x', '5 x', '6 x', '8 x', '10 x'],
      48: [],
      49: ['wedge', 'wing', '2 x', '3 x', '4 x', '6 x', '7 x', '8 x'],
      50: [],
      51: [],
      52: ['gear', 'tooth', 'holes'],
      53: [],
      54: [],
      55: [],
      56: [],
      57: ['duplo', 'fabuland'],
      58: [],
      59: ['scars', 'glasses', 'teeth', 'wrinkles', 'beard', 'moustache', 'smile', 'bandage', 'freckles', 'angry', 'yellow', 'white', 'blue', 'orange', 'pink', 'red', 'green'],
      60: ['arm', 'torso', 'mechanical', 'hand', 'yellow', 'black', 'white', 'blue', 'red', 'green', 'orange', 'shirt', 'tie', 'armor', 'jacket', 'robe', 'dress'],
      61: ['black', 'yellow', 'blue', 'green', 'red', 'orange', 'white', 'grey'],
      62: [],
      63: [],
      64: [],
      65: ['hair', 'helmet', 'hat', 'mask', 'pigtail', 'rebel', 'stormtrooper', 'hood', 'wrap'],
      66: ['tile', 'window', 'slope', 'internal', '1 x', '2 x', '3 x'],
      67: ['1', 'x', 'tile', 'round', '2', 'black', 'bottom', 'stud', 'holder'],
      68: ['disk', 'launcher', 'disc', 'projectile'],
      69: ['flame', 'wave'],
      70: ['tail', 'skirt'],
      71: ['cape', 'armor', 'shoulder', 'breastplate', 'necklace'],
      72: ['headwear', 'visor', 'mask', 'feather', 'plume'],
      73: ['weapon', 'shield', 'sword', 'gun', 'blaster', 'axe', 'bow', 'tool'],
      74: [],
      75: ['dinosaur', 'head', 'dragon', 'body', 'wing', 'crocodile', 'horse', 'tail', 'arm', 'leg'],
      76: ['plant', 'tree', 'flower'],
      77: [],
      78: []
    };
window.PREDEFINED_KEYWORDS = PREDEFINED_KEYWORDS;